<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeTypeInterface;

/**
 * @file
 * Contains notification timeline hook implementations.
 */

/**
 * Implements hook_theme().
 */
function notification_timeline_theme() {
  return array(
    'notification_timeline' => array(
      'variables' => array(
        'node' => NULL,
        'notifications' => array(),
        'segments' => array()
      ),
      'file' => 'notification_timeline.theme.inc',
      'template' => 'notification-timeline',
    ),
  );
}

/**
 * Implements hook_form_node_type_form_alter().
 */
function notification_timeline_form_node_type_form_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\node\NodeTypeInterface $type */
  $type = $form_state->getFormObject()->getEntity();
  $form['notification_timeline'] = array(
    '#type' => 'details',
    '#title' => t('Timeline'),
    '#weight' => 35,
    '#group' => 'additional_settings',
  );

  $form['notification_timeline']['notification_timeline_enable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable the notification timeline for this content type'),
    '#default_value' => $type->getThirdPartySetting('notification_timeline', 'enabled', FALSE),
  );

  $form['#entity_builders'][] = 'notification_timeline_form_node_type_form_builder';
}

/**
 * Entity builder for the node type form with timeline options.
 *
 * @see notification_timeline_form_node_type_form_alter().
 */
function notification_timeline_form_node_type_form_builder($entity_type, NodeTypeInterface $type, &$form, FormStateInterface $form_state) {
  $type->setThirdPartySetting('notification_timeline', 'enabled', $form_state->getValue('notification_timeline_enable'));
}

/**
 * Implements hook_form_ENTITY_TYPE_alter().
 *
 * Adds ajax functionality to the notification entity form.
 */
function notification_entity_form_notification_entity_form_alter(&$form, FormStateInterface $form_state) {

  $path = \Drupal::routeMatch()->getRouteObject()->getPath();
  $node = \Drupal::request()->attributes->get('node');

  if (strpos($path, '/node/{node}/timeline') === 0 && $node) {
    $form['actions']['submit']['#ajax'] = [
      'callback' => '\Drupal\notification_timeline\Controller\NotificationTimelineAjaxController::ajaxSubmitNotificationEntity',
      'path' => 'node/' . $node->id() . '/timeline/ajax/add',
    ];
  }
}

/**
 * Implements hook_views_data_alter().
 *
 * Adds a timeline link to nodes.
 */
function notification_timeline_views_data_alter(array &$data) {
  if (isset($data['node']['edit_node'])) {
    $data['node']['notification_timeline'] = array(
      'field' => array(
        'title' => t('Link to timeline'),
        'help' => t('Provide a simple link to the event timeline.'),
        'id' => 'node_link_timeline',
      ),
    );
  }
}