<?php
/**
 * @file
 * Contains Drupal\notification_entity\notification_entity.module
 */

function notification_entity_type_load() {

}

/**
 * Implements hook_theme().
 */
function notification_entity_theme() {
  return array(
    'notification_entity_add_list' => array(
      'variables' => array('content' => NULL),
      'file' => 'notification_entity.pages.inc',
      'template' => 'notification_entity-add-list',
    ),
    'notification_entity' => array(
      'render element' => 'elements',
      'file' => 'notification_entity.pages.inc',
      'template' => 'notification_entity',
    ),
  );
}