<?php

/**
 * @file
 * Functions to support theming in the LISSA Bluedrop theme.
 */

/**
 * Implements hook_preprocess_page().
 */
function lissa_bluedrop_preprocess_page(&$variables) {
  // Add tooltip functionality to forms.
  $libraries = array(
    '#attached' => array(
      'library' => array(
        'lissa_bluedrop/form.tooltips',
        'lissa_bluedrop/form.selectize',
      ),
    ),
  );
  drupal_render($libraries);
}