<?php

/**
 * @file
 * Contains hook implementations for the lissa_kickstart_core module.
 */

/**
 * Implements hook_editor_js_settings_alter().
 *
 * Reduce the editor size.
 */
function lissa_kickstart_core_editor_js_settings_alter(array &$settings) {
  if (isset($settings['editor']['formats']['full_html'])) {
    $settings['editor']['formats']['full_html']['editorSettings']['height'] = 80;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function lissa_kickstart_core_form_user_login_form_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][] = '\Drupal\lissa_kickstart_core\Controller\LissaKickstartCoreController::redirectLoginForm';
}
