<?php
/**
 * @file
 * The module that sends notifications to twitter
 */

use \Drupal\Core\Entity\EntityInterface;
use Codebird\Codebird;
use Drupal\notification_entity\Entity\NotificationEntity;

/**
 * Implements hook_entity_insert()
 * @param EntityInterface $notification
 */
function notification_twitter_entity_insert(EntityInterface $notification) {
  if ($notification->getEntityTypeId() == 'notification_entity') {
    notification_tweet($notification);
  }
}

/**
 * Implements hook_entity_update()
 * @param EntityInterface $notification
 */
function notification_twitter_entity_update(EntityInterface $notification) {
  if ($notification->getEntityTypeId() == 'notification_entity') {
    notification_tweet($notification, 'update');
  }
}

/**
 * Implements hook_entity_delete()
 *
 * @param EntityInterface $notification
 */
function notification_twitter_entity_delete(EntityInterface $notification) {
  if ($notification->getEntityTypeId() == 'notification_entity') {
    notification_tweet($notification, 'delete');
  }
}

/**
 * Pushes a notification to twitter.
 *
 * @param NotificationEntity $notificationEntity
 */
function notification_tweet(NotificationEntity $notificationEntity) {
  $config = \Drupal::config('notification_twitter.settings');

  $cb = new Codebird();

  $cb->setToken(
    $config->get('access_token'),
    $config->get('access_token_secret')
  );

  $cb->setConsumerKey(
    $config->get('consumer_key'),
    $config->get('consumer_secret')
  );

  $params = [
    'status' => $notificationEntity->getTitle()
  ];

  $reply = $cb->statuses_update($params);

  // TODO: handle error messages
}
